server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/books/**
        - id: student-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/students/**
